spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver    #   MySQL5???MySQL;
  mvc:
    format:
      date: dd-MM-yyyy
server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.example.sherry.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml



